"""
Professional PDF Report Generator
"""

from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_pdf(
    patient,
    prediction,
    probability,
    clinical_summary,
    recommendations,
    ai_explanation
):
    """
    Generate CardioAI PDF Report.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    story = []

    # =====================================================
    # Title
    # =====================================================

    story.append(

        Paragraph(

            "<font size=24 color='darkred'><b>❤️ CardioAI</b></font>",

            styles["Title"]

        )

    )

    story.append(

        Paragraph(

            "<b>Explainable Cardiac Risk Assessment Report</b>",

            styles["Heading2"]

        )

    )

    story.append(Spacer(1, 20))

    # =====================================================
    # Patient Table
    # =====================================================

    patient_table = [["Patient Information", "Value"]]

    for key, value in patient.items():

        patient_table.append(

            [str(key), str(value)]

        )

    table = Table(patient_table)

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

        ])

    )

    story.append(table)

    story.append(Spacer(1, 20))

    # =====================================================
    # Prediction
    # =====================================================

    story.append(

        Paragraph(

            "<b>Prediction Summary</b>",

            styles["Heading2"]

        )

    )

    story.append(

        Paragraph(

            f"<b>Prediction:</b> {prediction}",

            styles["BodyText"]

        )

    )

    story.append(

        Paragraph(

            f"<b>Risk Probability:</b> {probability*100:.2f}%",

            styles["BodyText"]

        )

    )

    story.append(Spacer(1, 15))

    # =====================================================
    # Clinical Summary
    # =====================================================

    story.append(

        Paragraph(

            "<b>Clinical Summary</b>",

            styles["Heading2"]

        )

    )

    for key, value in clinical_summary.items():

        story.append(

            Paragraph(

                f"• <b>{key}</b>: {value}",

                styles["BodyText"]

            )

        )

    story.append(Spacer(1, 15))

    # =====================================================
    # Recommendations
    # =====================================================

    story.append(

        Paragraph(

            "<b>Personalized Recommendations</b>",

            styles["Heading2"]

        )

    )

    for item in recommendations:

        story.append(

            Paragraph(

                f"• {item['Recommendation']}",

                styles["BodyText"]

            )

        )

    story.append(Spacer(1, 15))

    # =====================================================
    # AI Explanation
    # =====================================================

    story.append(

        Paragraph(

            "<b>AI Clinical Explanation</b>",

            styles["Heading2"]

        )

    )

    story.append(

        Paragraph(

            ai_explanation.replace("\n", "<br/>"),

            styles["BodyText"]

        )

    )

    story.append(Spacer(1, 20))

    # =====================================================
    # Footer
    # =====================================================

    story.append(

        Paragraph(

            f"Generated on : {datetime.now().strftime('%d-%m-%Y %H:%M')}",

            styles["Italic"]

        )

    )

    story.append(Spacer(1, 10))

    story.append(

        Paragraph(

            "<font color='red'><b>Disclaimer:</b> "
            "This report is generated by CardioAI for educational purposes only. "
            "It should not replace professional medical advice.</font>",

            styles["BodyText"]

        )

    )

    doc.build(story)

    buffer.seek(0)

    return buffer